# Generated by Django 4.2.7 on 2025-09-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
